# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "tfstate2"
    key                  = "./terraform.tfstate"
    resource_group_name  = "Ajinkya-RG1"
    storage_account_name = "store1822"
  }
}
